events {}
http {
    server {
        listen 80;

        location /api/ {
            proxy_pass http://scooter-app:8080;
            proxy_set_header Host $host;
        }

        location /scooter-violations/ {
            proxy_pass http://minio:9000;
            proxy_set_header Host minio:9000;
            client_max_body_size 4G;
        }
    }
}