models:
  detection:
    model_path: models/detection/best.pt
    confidence_threshold: 0.44
    iou_threshold: 0.75

  pose_estimation:
    model_path: models/pose_classification/yolo11m-pose.pt

  pose_classification:
    ensemble_paths:
      [
        models/pose_classification/pose_classifier_B.joblib,
        models/pose_classification/pose_classifier.joblib,
      ]
    ensemble_weights: [1, 0]

  segmentation:
    segmentation_model: "facebook/mask2former-swin-large-mapillary-vistas-semantic"